### ISSUE TITLE
What to do when I get a Timeout Error

### ISSUE THREAD

**Issue by timothyjoh** [dcrec1/signal#1]
What to look at when I get the following
Timeout::Error (execution expired):
  /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/timeout.rb:60:in `open'
  /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/smtp.rb:551:in`do_start'
  /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/smtp.rb:551:in `do_start'
  /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/smtp.rb:525:in`start'
  app/models/build.rb:21:in `after_create'
  haml (2.2.9) rails/./lib/sass/plugin/rails.rb:19:in`process'

**Comment by dcrec1** [comment]
This error happens in some servers when the build is being created by the interface and it takes a little bit to complete.

This error doesn't seems to happen with Passenger, but if you're using Mongrel, you can set the timeout with -o, like this:

mongrel_rails start -o <time in seconds>

When build is created by pinging /projects/name/build this error doesn't happen because the build is done in the background, with delajed_job. Maybe it's a good idea to also use it when the build is created by the interface.

**Comment by millisami** [comment]
I've setup the signal and used with Mongrel on my dev machine. The Timeout error. 
Got on this page, setup with passenger but still the Timeout error.
This might be due to the project url on github, so go through net. How can I configure passenger (what config variable) to increase execution time?

**Comment by dcrec1** [comment]
Can you plz post here the stack trace? I think the error may be coming from a library and not from Passenger.
